const xAxisData = [
    {
        name: "Jan",
        Sale: 112000,
    },
    {
        name: "Feb",
        Sale: 98000,
    },
    {
        name: "Mar",
        Sale: 124000,
    },
    {
        name: "Apr",
        Sale: 137000,
    },
    {
        name: "May",
        Sale: 92000,
    },
    {
        name: "Jun",
        Sale: 115000,
    },
    {
        name: "Jul",
        Sale: 105000,
    },
    {
        name: "Aug",
        Sale: 120000,
    },
    {
        name: "Sep",
        Sale: 140000,
    },
    {
        name: "Oct",
        Sale: 132000,
    },
    {
        name: "Nov",
        Sale: 128000,
    },
    {
        name: "Dec",
        Sale: 150000,
    },
    {
        name: "Jan",
        Sale: 118000,
    },
    {
        name: "Feb",
        Sale: 102000,
    },
    {
        name: "Mar",
        Sale: 125000,
    },
    {
        name: "Apr",
        Sale: 130000,
    },
    {
        name: "May",
        Sale: 95000,
    },
    {
        name: "Jun",
        Sale: 110000,
    },
    {
        name: "Jul",
        Sale: 108000,
    },
    {
        name: "Aug",
        Sale: 122000,
    },
    {
        name: "Sep",
        Sale: 138000,
    },
    {
        name: "Oct",
        Sale: 135000,
    },
    {
        name: "Nov",
        Sale: 126000,
    },
    {
        name: "Dec",
        Sale: 152000,
    },
    {
        name: "Jan",
        Sale: 116000,
    },
    {
        name: "Feb",
        Sale: 99000,
    },
    {
        name: "Mar",
        Sale: 128000,
    },
    {
        name: "Apr",
        Sale: 133000,
    },
    {
        name: "May",
        Sale: 97000,
    },
    {
        name: "Jun",
        Sale: 112000,
    },
    {
        name: "Jul",
        Sale: 107000,
    },
    {
        name: "Aug",
        Sale: 121000,
    },
    {
        name: "Sep",
        Sale: 136000,
    },
    {
        name: "Oct",
        Sale: 130000,
    },
    {
        name: "Nov",
        Sale: 129000,
    },
    {
        name: "Dec",
        Sale: 148000,
    },
    {
        name: "Jan",
        Sale: 120000,
    },
    {
        name: "Feb",
        Sale: 101000,
    },
    {
        name: "Mar",
        Sale: 127000,
    },
    {
        name: "Apr",
        Sale: 131000,
    },
    {
        name: "May",
        Sale: 93000,
    },
    {
        name: "Jun",
        Sale: 113000,
    },
    {
        name: "Jul",
        Sale: 109000,
    },
    {
        name: "Aug",
        Sale: 119000,
    },
    {
        name: "Sep",
        Sale: 141000,
    },
    {
        name: "Oct",
        Sale: 134000,
    },
    {
        name: "Nov",
        Sale: 123000,
    },
    {
        name: "Dec",
        Sale: 151000,
    },
];

const newMembers = [
    {
        id: 1,
        username: "Mohammad Amin",
        title: "Web Developer",
        img: "/Images/face (1).jpg",
    },
    {
        id: 2,
        username: "Sarah Johnson",
        title: "UI/UX Designer",
        img: "/Images/face (2).jpg",
    },
    {
        id: 3,
        username: "John Doe",
        title: "Full Stack Developer",
        img: "/Images/face (3).jpg",
    },
    {
        id: 4,
        username: "Alice Smith",
        title: "Software Engineer",
        img: "/Images/face (4).jpg",
    },
    {
        id: 5,
        username: "Bob Brown",
        title: "Frontend Developer",
        img: "/Images/face (5).jpg",
    },
    {
        id: 6,
        username: "Emily White",
        title: "Backend Developer",
        img: "/Images/face (6).jpg",
    },
    {
        id: 7,
        username: "Frank Green",
        title: "Data Scientist",
        img: "/Images/face (7).jpg",
    },
    {
        id: 8,
        username: "Grace Lee",
        title: "Project Manager",
        img: "/Images/face (8).jpg",
    },
    {
        id: 9,
        username: "Henry Wilson",
        title: "DevOps Engineer",
        img: "/Images/face (9).jpg",
    },
    {
        id: 10,
        username: "Isabella Clark",
        title: "QA Engineer",
        img: "/Images/face (10).jpg",
    },
    {
        id: 11,
        username: "Jack Davis",
        title: "Mobile Developer",
        img: "/Images/face (11).jpg",
    },
    {
        id: 12,
        username: "Karen Martinez",
        title: "Systems Analyst",
        img: "/Images/face (12).jpg",
    },
    {
        id: 13,
        username: "Larry Rodriguez",
        title: "Network Engineer",
        img: "/Images/face (13).jpg",
    },
    {
        id: 14,
        username: "Megan Hernandez",
        title: "Database Administrator",
        img: "/Images/face (14).jpg",
    },
    {
        id: 15,
        username: "Nina Hall",
        title: "Security Analyst",
        img: "/Images/face (15).jpg",
    },
    {
        id: 16,
        username: "Oscar Young",
        title: "Cloud Engineer",
        img: "/Images/face (16).jpg",
    },
    {
        id: 17,
        username: "Paul King",
        title: "IT Support Specialist",
        img: "/Images/face (17).jpg",
    },
    {
        id: 18,
        username: "Quincy Scott",
        title: "Product Manager",
        img: "/Images/face (18).jpg",
    },
    {
        id: 19,
        username: "Rachel Walker",
        title: "Technical Writer",
        img: "/Images/face (19).jpg",
    },
    {
        id: 20,
        username: "Steve Baker",
        title: "Web Developer",
        img: "/Images/face (20).jpg",
    },
    {
        id: 21,
        username: "Tina Adams",
        title: "Software Tester",
        img: "/Images/face (21).jpg",
    },
    {
        id: 22,
        username: "Uma Phillips",
        title: "SEO Specialist",
        img: "/Images/face (22).jpg",
    },
    {
        id: 23,
        username: "Victor Cooper",
        title: "Content Strategist",
        img: "/Images/face (23).jpg",
    },
    {
        id: 24,
        username: "Wendy Ward",
        title: "Graphic Designer",
        img: "/Images/face (24).jpg",
    },
    {
        id: 25,
        username: "Xander Perez",
        title: "UI/UX Designer",
        img: "/Images/face (25).jpg",
    },
    {
        id: 26,
        username: "Yara Collins",
        title: "Full Stack Developer",
        img: "/Images/face (26).jpg",
    },
    {
        id: 27,
        username: "Zane Sanchez",
        title: "Frontend Developer",
        img: "/Images/face (27).jpg",
    },
    {
        id: 28,
        username: "Alan Rivera",
        title: "Backend Developer",
        img: "/Images/face (28).jpg",
    },
    {
        id: 29,
        username: "Bella Morgan",
        title: "Data Scientist",
        img: "/Images/face (29).jpg",
    },
    {
        id: 30,
        username: "Cameron Reed",
        title: "Project Manager",
        img: "/Images/face (30).jpg",
    },
    {
        id: 31,
        username: "Diana Cook",
        title: "DevOps Engineer",
        img: "/Images/face (31).jpg",
    },
    {
        id: 32,
        username: "Evan Rogers",
        title: "QA Engineer",
        img: "/Images/face (32).jpg",
    },
    {
        id: 33,
        username: "Fiona Foster",
        title: "Mobile Developer",
        img: "/Images/face (33).jpg",
    },
    {
        id: 34,
        username: "George Gonzales",
        title: "Systems Analyst",
        img: "/Images/face (34).jpg",
    },
    {
        id: 35,
        username: "Hannah Hayes",
        title: "Network Engineer",
        img: "/Images/face (35).jpg",
    },
    {
        id: 36,
        username: "Isaac Myers",
        title: "Database Administrator",
        img: "/Images/face (36).jpg",
    },
    {
        id: 37,
        username: "Jasmine Ross",
        title: "Security Analyst",
        img: "/Images/face (37).jpg",
    },
    {
        id: 38,
        username: "Kevin Powell",
        title: "Cloud Engineer",
        img: "/Images/face (38).jpg",
    },
    {
        id: 39,
        username: "Lily Jenkins",
        title: "IT Support Specialist",
        img: "/Images/face (39).jpg",
    },
    {
        id: 40,
        username: "Mason Perry",
        title: "Product Manager",
        img: "/Images/face (40).jpg",
    },
    {
        id: 41,
        username: "Natalie Henderson",
        title: "Technical Writer",
        img: "/Images/face (41).jpg",
    },
    {
        id: 42,
        username: "Oliver Coleman",
        title: "Web Developer",
        img: "/Images/face (42).jpg",
    },
    {
        id: 43,
        username: "Penelope Howard",
        title: "Software Tester",
        img: "/Images/face (43).jpg",
    },
    {
        id: 44,
        username: "Quinn Barnes",
        title: "SEO Specialist",
        img: "/Images/face (44).jpg",
    },
    {
        id: 45,
        username: "Ryan Simpson",
        title: "Content Strategist",
        img: "/Images/face (45).jpg",
    },
    {
        id: 46,
        username: "Sophie Grant",
        title: "Graphic Designer",
        img: "/Images/face (46).jpg",
    },
    {
        id: 47,
        username: "Thomas Fisher",
        title: "UI/UX Designer",
        img: "/Images/face (47).jpg",
    },
    {
        id: 48,
        username: "Uma Rivera",
        title: "Full Stack Developer",
        img: "/Images/face (48).jpg",
    },
    {
        id: 49,
        username: "Victor Bell",
        title: "Frontend Developer",
        img: "/Images/face (49).jpg",
    },
    {
        id: 50,
        username: "Wendy Carter",
        title: "Backend Developer",
        img: "/Images/face (50).jpg",
    },
];

const transactions = [
    {
        id: 1,
        customer: "Qadir Yolme",
        date: "12 Jun 2022",
        amount: 123,
        status: "Approved",
        img: "/Images/face (1).jpg",
    },
    {
        id: 2,
        customer: "Sarah Johnson",
        date: "15 Jul 2022",
        amount: 250,
        status: "Declined",
        img: "/Images/face (2).jpg",
    },
    {
        id: 3,
        customer: "John Doe",
        date: "22 Aug 2022",
        amount: 300,
        status: "Pending",
        img: "/Images/face (3).jpg",
    },
    {
        id: 4,
        customer: "Alice Smith",
        date: "01 Sep 2022",
        amount: 450,
        status: "Approved",
        img: "/Images/face (4).jpg",
    },
    {
        id: 5,
        customer: "Bob Brown",
        date: "10 Oct 2022",
        amount: 500,
        status: "Declined",
        img: "/Images/face (5).jpg",
    },
    {
        id: 6,
        customer: "Emily White",
        date: "15 Nov 2022",
        amount: 600,
        status: "Pending",
        img: "/Images/face (6).jpg",
    },
    {
        id: 7,
        customer: "Frank Green",
        date: "20 Dec 2022",
        amount: 700,
        status: "Approved",
        img: "/Images/face (7).jpg",
    },
    {
        id: 8,
        customer: "Grace Lee",
        date: "25 Jan 2023",
        amount: 800,
        status: "Declined",
        img: "/Images/face (8).jpg",
    },
    {
        id: 9,
        customer: "Henry Wilson",
        date: "05 Feb 2023",
        amount: 900,
        status: "Pending",
        img: "/Images/face (9).jpg",
    },
    {
        id: 10,
        customer: "Isabella Clark",
        date: "10 Mar 2023",
        amount: 1000,
        status: "Approved",
        img: "/Images/face (10).jpg",
    },
    {
        id: 11,
        customer: "Jack Davis",
        date: "15 Apr 2023",
        amount: 1100,
        status: "Declined",
        img: "/Images/face (11).jpg",
    },
    {
        id: 12,
        customer: "Karen Martinez",
        date: "20 May 2023",
        amount: 1200,
        status: "Pending",
        img: "/Images/face (12).jpg",
    },
    {
        id: 13,
        customer: "Larry Rodriguez",
        date: "25 Jun 2023",
        amount: 1300,
        status: "Approved",
        img: "/Images/face (13).jpg",
    },
    {
        id: 14,
        customer: "Megan Hernandez",
        date: "01 Jul 2023",
        amount: 1400,
        status: "Declined",
        img: "/Images/face (14).jpg",
    },
    {
        id: 15,
        customer: "Nina Hall",
        date: "10 Aug 2023",
        amount: 1500,
        status: "Pending",
        img: "/Images/face (15).jpg",
    },
    {
        id: 16,
        customer: "Oscar Young",
        date: "15 Sep 2023",
        amount: 1600,
        status: "Approved",
        img: "/Images/face (16).jpg",
    },
    {
        id: 17,
        customer: "Paul King",
        date: "20 Oct 2023",
        amount: 1700,
        status: "Declined",
        img: "/Images/face (17).jpg",
    },
    {
        id: 18,
        customer: "Quincy Scott",
        date: "25 Nov 2023",
        amount: 1800,
        status: "Pending",
        img: "/Images/face (18).jpg",
    },
    {
        id: 19,
        customer: "Rachel Walker",
        date: "01 Dec 2023",
        amount: 1900,
        status: "Approved",
        img: "/Images/face (19).jpg",
    },
    {
        id: 20,
        customer: "Steve Baker",
        date: "10 Jan 2024",
        amount: 2000,
        status: "Declined",
        img: "/Images/face (20).jpg",
    },
    {
        id: 21,
        customer: "Tina Adams",
        date: "15 Feb 2024",
        amount: 2100,
        status: "Pending",
        img: "/Images/face (21).jpg",
    },
    {
        id: 22,
        customer: "Uma Phillips",
        date: "20 Mar 2024",
        amount: 2200,
        status: "Approved",
        img: "/Images/face (22).jpg",
    },
    {
        id: 23,
        customer: "Victor Cooper",
        date: "25 Apr 2024",
        amount: 2300,
        status: "Declined",
        img: "/Images/face (23).jpg",
    },
    {
        id: 24,
        customer: "Wendy Ward",
        date: "01 May 2024",
        amount: 2400,
        status: "Pending",
        img: "/Images/face (24).jpg",
    },
    {
        id: 25,
        customer: "Xander Perez",
        date: "10 Jun 2024",
        amount: 2500,
        status: "Approved",
        img: "/Images/face (25).jpg",
    },
    {
        id: 26,
        customer: "Yara Collins",
        date: "15 Jul 2024",
        amount: 2600,
        status: "Declined",
        img: "/Images/face (26).jpg",
    },
    {
        id: 27,
        customer: "Zane Sanchez",
        date: "20 Aug 2024",
        amount: 2700,
        status: "Pending",
        img: "/Images/face (27).jpg",
    },
    {
        id: 28,
        customer: "Alan Rivera",
        date: "25 Sep 2024",
        amount: 2800,
        status: "Approved",
        img: "/Images/face (28).jpg",
    },
    {
        id: 29,
        customer: "Bella Morgan",
        date: "01 Oct 2024",
        amount: 2900,
        status: "Declined",
        img: "/Images/face (29).jpg",
    },
    {
        id: 30,
        customer: "Cameron Reed",
        date: "10 Nov 2024",
        amount: 3000,
        status: "Pending",
        img: "/Images/face (30).jpg",
    },
    {
        id: 31,
        customer: "Diana Cook",
        date: "15 Dec 2024",
        amount: 3100,
        status: "Approved",
        img: "/Images/face (31).jpg",
    },
    {
        id: 32,
        customer: "Evan Rogers",
        date: "20 Jan 2025",
        amount: 3200,
        status: "Declined",
        img: "/Images/face (32).jpg",
    },
    {
        id: 33,
        customer: "Fiona Foster",
        date: "25 Feb 2025",
        amount: 3300,
        status: "Pending",
        img: "/Images/face (33).jpg",
    },
    {
        id: 34,
        customer: "George Gonzales",
        date: "01 Mar 2025",
        amount: 3400,
        status: "Approved",
        img: "/Images/face (34).jpg",
    },
    {
        id: 35,
        customer: "Hannah Hayes",
        date: "10 Apr 2025",
        amount: 3500,
        status: "Declined",
        img: "/Images/face (35).jpg",
    },
    {
        id: 36,
        customer: "Isaac Myers",
        date: "15 May 2025",
        amount: 3600,
        status: "Pending",
        img: "/Images/face (36).jpg",
    },
    {
        id: 37,
        customer: "Jasmine Ross",
        date: "20 Jun 2025",
        amount: 3700,
        status: "Approved",
        img: "/Images/face (37).jpg",
    },
    {
        id: 38,
        customer: "Kevin Powell",
        date: "25 Jul 2025",
        amount: 3800,
        status: "Declined",
        img: "/Images/face (38).jpg",
    },
    {
        id: 39,
        customer: "Lily Jenkins",
        date: "01 Aug 2025",
        amount: 3900,
        status: "Pending",
        img: "/Images/face (39).jpg",
    },
    {
        id: 40,
        customer: "Mason Perry",
        date: "10 Sep 2025",
        amount: 4000,
        status: "Approved",
        img: "/Images/face (40).jpg",
    },
    {
        id: 41,
        customer: "Natalie Henderson",
        date: "15 Oct 2025",
        amount: 4100,
        status: "Declined",
        img: "/Images/face (41).jpg",
    },
    {
        id: 42,
        customer: "Oliver Coleman",
        date: "20 Nov 2025",
        amount: 4200,
        status: "Pending",
        img: "/Images/face (42).jpg",
    },
    {
        id: 43,
        customer: "Penelope Howard",
        date: "25 Dec 2025",
        amount: 4300,
        status: "Approved",
        img: "/Images/face (43).jpg",
    },
    {
        id: 44,
        customer: "Quinn Barnes",
        date: "01 Jan 2026",
        amount: 4400,
        status: "Declined",
        img: "/Images/face (44).jpg",
    },
    {
        id: 45,
        customer: "Ryan Simpson",
        date: "10 Feb 2026",
        amount: 4500,
        status: "Pending",
        img: "/Images/face (45).jpg",
    },
    {
        id: 46,
        customer: "Sophie Grant",
        date: "15 Mar 2026",
        amount: 4600,
        status: "Approved",
        img: "/Images/face (46).jpg",
    },
    {
        id: 47,
        customer: "Thomas Fisher",
        date: "20 Apr 2026",
        amount: 4700,
        status: "Declined",
        img: "/Images/face (47).jpg",
    },
    {
        id: 48,
        customer: "Uma Rivera",
        date: "25 May 2026",
        amount: 4800,
        status: "Pending",
        img: "/Images/face (48).jpg",
    },
    {
        id: 49,
        customer: "Victor Bell",
        date: "01 Jun 2026",
        amount: 4900,
        status: "Approved",
        img: "/Images/face (49).jpg",
    },
    {
        id: 50,
        customer: "Wendy Carter",
        date: "10 Jul 2026",
        amount: 5000,
        status: "Declined",
        img: "/Images/face (50).jpg",
    },
];

const userRows = [
    {
        id: 1,
        username: "Qadir Yolme",
        avatar: "/Images/face (1).jpg",
        status: "active",
        transaction: "$129.52",
        email: "qadiryoulme524@gmail.com",
    },
    {
        id: 2,
        username: "Sarah Johnson",
        avatar: "/Images/face (2).jpg",
        status: "inactive",
        transaction: "$150.00",
        email: "sarah.johnson@gmail.com",
    },
    {
        id: 3,
        username: "John Doe",
        avatar: "/Images/face (3).jpg",
        status: "active",
        transaction: "$200.75",
        email: "john.doe@gmail.com",
    },
    {
        id: 4,
        username: "Alice Smith",
        avatar: "/Images/face (4).jpg",
        status: "active",
        transaction: "$340.20",
        email: "alice.smith@gmail.com",
    },
    {
        id: 5,
        username: "Bob Brown",
        avatar: "/Images/face (5).jpg",
        status: "inactive",
        transaction: "$99.99",
        email: "bob.brown@gmail.com",
    },
    {
        id: 6,
        username: "Emily White",
        avatar: "/Images/face (6).jpg",
        status: "active",
        transaction: "$185.60",
        email: "emily.white@gmail.com",
    },
    {
        id: 7,
        username: "Frank Green",
        avatar: "/Images/face (7).jpg",
        status: "active",
        transaction: "$450.00",
        email: "frank.green@gmail.com",
    },
    {
        id: 8,
        username: "Grace Lee",
        avatar: "/Images/face (8).jpg",
        status: "inactive",
        transaction: "$120.55",
        email: "grace.lee@gmail.com",
    },
    {
        id: 9,
        username: "Henry Wilson",
        avatar: "/Images/face (9).jpg",
        status: "active",
        transaction: "$330.80",
        email: "henry.wilson@gmail.com",
    },
    {
        id: 10,
        username: "Isabella Clark",
        avatar: "/Images/face (10).jpg",
        status: "active",
        transaction: "$215.40",
        email: "isabella.clark@gmail.com",
    },
    {
        id: 11,
        username: "Jack Davis",
        avatar: "/Images/face (11).jpg",
        status: "inactive",
        transaction: "$180.75",
        email: "jack.davis@gmail.com",
    },
    {
        id: 12,
        username: "Karen Martinez",
        avatar: "/Images/face (12).jpg",
        status: "active",
        transaction: "$230.60",
        email: "karen.martinez@gmail.com",
    },
    {
        id: 13,
        username: "Larry Rodriguez",
        avatar: "/Images/face (13).jpg",
        status: "inactive",
        transaction: "$145.80",
        email: "larry.rodriguez@gmail.com",
    },
    {
        id: 14,
        username: "Megan Hernandez",
        avatar: "/Images/face (14).jpg",
        status: "active",
        transaction: "$340.20",
        email: "megan.hernandez@gmail.com",
    },
    {
        id: 15,
        username: "Nina Hall",
        avatar: "/Images/face (15).jpg",
        status: "active",
        transaction: "$195.60",
        email: "nina.hall@gmail.com",
    },
    {
        id: 16,
        username: "Oscar Young",
        avatar: "/Images/face (16).jpg",
        status: "inactive",
        transaction: "$99.99",
        email: "oscar.young@gmail.com",
    },
    {
        id: 17,
        username: "Paul King",
        avatar: "/Images/face (17).jpg",
        status: "active",
        transaction: "$425.40",
        email: "paul.king@gmail.com",
    },
    {
        id: 18,
        username: "Quincy Scott",
        avatar: "/Images/face (18).jpg",
        status: "active",
        transaction: "$200.00",
        email: "quincy.scott@gmail.com",
    },
    {
        id: 19,
        username: "Rachel Walker",
        avatar: "/Images/face (19).jpg",
        status: "inactive",
        transaction: "$150.55",
        email: "rachel.walker@gmail.com",
    },
    {
        id: 20,
        username: "Steve Baker",
        avatar: "/Images/face (20).jpg",
        status: "active",
        transaction: "$399.99",
        email: "steve.baker@gmail.com",
    },
    {
        id: 21,
        username: "Tina Adams",
        avatar: "/Images/face (21).jpg",
        status: "inactive",
        transaction: "$129.99",
        email: "tina.adams@gmail.com",
    },
    {
        id: 22,
        username: "Uma Phillips",
        avatar: "/Images/face (22).jpg",
        status: "active",
        transaction: "$215.75",
        email: "uma.phillips@gmail.com",
    },
    {
        id: 23,
        username: "Victor Cooper",
        avatar: "/Images/face (23).jpg",
        status: "active",
        transaction: "$315.45",
        email: "victor.cooper@gmail.com",
    },
    {
        id: 24,
        username: "Wendy Ward",
        avatar: "/Images/face (24).jpg",
        status: "inactive",
        transaction: "$200.00",
        email: "wendy.ward@gmail.com",
    },
    {
        id: 25,
        username: "Xander Perez",
        avatar: "/Images/face (25).jpg",
        status: "active",
        transaction: "$425.60",
        email: "xander.perez@gmail.com",
    },
    {
        id: 26,
        username: "Yara Collins",
        avatar: "/Images/face (26).jpg",
        status: "inactive",
        transaction: "$129.75",
        email: "yara.collins@gmail.com",
    },
    {
        id: 27,
        username: "Zane Sanchez",
        avatar: "/Images/face (27).jpg",
        status: "active",
        transaction: "$245.80",
        email: "zane.sanchez@gmail.com",
    },
    {
        id: 28,
        username: "Alan Rivera",
        avatar: "/Images/face (28).jpg",
        status: "inactive",
        transaction: "$355.50",
        email: "alan.rivera@gmail.com",
    },
    {
        id: 29,
        username: "Bella Morgan",
        avatar: "/Images/face (29).jpg",
        status: "active",
        transaction: "$299.99",
        email: "bella.morgan@gmail.com",
    },
    {
        id: 30,
        username: "Cameron Reed",
        avatar: "/Images/face (30).jpg",
        status: "active",
        transaction: "$375.25",
        email: "cameron.reed@gmail.com",
    },
    {
        id: 31,
        username: "Diana Cook",
        avatar: "/Images/face (31).jpg",
        status: "inactive",
        transaction: "$189.99",
        email: "diana.cook@gmail.com",
    },
    {
        id: 32,
        username: "Evan Rogers",
        avatar: "/Images/face (32).jpg",
        status: "active",
        transaction: "$450.00",
        email: "evan.rogers@gmail.com",
    },
    {
        id: 33,
        username: "Fiona Foster",
        avatar: "/Images/face (33).jpg",
        status: "active",
        transaction: "$199.99",
        email: "fiona.foster@gmail.com",
    },
    {
        id: 34,
        username: "George Gonzales",
        avatar: "/Images/face (34).jpg",
        status: "inactive",
        transaction: "$215.50",
        email: "george.gonzales@gmail.com",
    },
    {
        id: 35,
        username: "Hannah Hayes",
        avatar: "/Images/face (35).jpg",
        status: "active",
        transaction: "$325.80",
        email: "hannah.hayes@gmail.com",
    },
    {
        id: 36,
        username: "Isaac Myers",
        avatar: "/Images/face (36).jpg",
        status: "inactive",
        transaction: "$250.00",
        email: "isaac.myers@gmail.com",
    },
    {
        id: 37,
        username: "Jasmine Ross",
        avatar: "/Images/face (37).jpg",
        status: "active",
        transaction: "$299.99",
        email: "jasmine.ross@gmail.com",
    },
    {
        id: 38,
        username: "Kevin Powell",
        avatar: "/Images/face (38).jpg",
        status: "inactive",
        transaction: "$155.80",
        email: "kevin.powell@gmail.com",
    },
    {
        id: 39,
        username: "Lily Jenkins",
        avatar: "/Images/face (39).jpg",
        status: "active",
        transaction: "$245.99",
        email: "lily.jenkins@gmail.com",
    },
    {
        id: 40,
        username: "Mason Perry",
        avatar: "/Images/face (40).jpg",
        status: "inactive",
        transaction: "$300.00",
        email: "mason.perry@gmail.com",
    },
    {
        id: 41,
        username: "Natalie Henderson",
        avatar: "/Images/face (41).jpg",
        status: "active",
        transaction: "$175.25",
        email: "natalie.henderson@gmail.com",
    },
    {
        id: 42,
        username: "Oliver Coleman",
        avatar: "/Images/face (42).jpg",
        status: "active",
        transaction: "$425.75",
        email: "oliver.coleman@gmail.com",
    },
    {
        id: 43,
        username: "Penelope Howard",
        avatar: "/Images/face (43).jpg",
        status: "inactive",
        transaction: "$195.45",
        email: "penelope.howard@gmail.com",
    },
    {
        id: 44,
        username: "Quinn Barnes",
        avatar: "/Images/face (44).jpg",
        status: "active",
        transaction: "$350.00",
        email: "quinn.barnes@gmail.com",
    },
    {
        id: 45,
        username: "Ryan Simpson",
        avatar: "/Images/face (45).jpg",
        status: "inactive",
        transaction: "$210.75",
        email: "ryan.simpson@gmail.com",
    },
    {
        id: 46,
        username: "Sophie Grant",
        avatar: "/Images/face (46).jpg",
        status: "active",
        transaction: "$129.99",
        email: "sophie.grant@gmail.com",
    },
    {
        id: 47,
        username: "Thomas Fisher",
        avatar: "/Images/face (47).jpg",
        status: "inactive",
        transaction: "$215.80",
        email: "thomas.fisher@gmail.com",
    },
    {
        id: 48,
        username: "Uma Rivera",
        avatar: "/Images/face (48).jpg",
        status: "active",
        transaction: "$330.20",
        email: "uma.rivera@gmail.com",
    },
    {
        id: 49,
        username: "Victor Bell",
        avatar: "/Images/face (49).jpg",
        status: "inactive",
        transaction: "$199.99",
        email: "victor.bell@gmail.com",
    },
    {
        id: 50,
        username: "Wendy Carter",
        avatar: "/Images/face (50).jpg",
        status: "active",
        transaction: "$275.60",
        email: "wendy.carter@gmail.com",
    },
];

export { xAxisData, newMembers, transactions, userRows };

